const fs = require('fs')
const { VizhenerCipher } = require('./vizhener.js')
const {encrypted} = require('./encrypted.json')
const {maxPeriod, maxTableLength} = Object.fromEntries(process.argv.slice(2).map(x => x.slice(2).split('=')))
console.log(process.argv)

const vizhener = new VizhenerCipher(encrypted, maxPeriod, maxTableLength)
console.log('Розшифровка методом першим знаходження ключа...')
const decrypted1 = vizhener.decryptReliable({method: 1})
fs.writeFileSync('Decrypted1.txt', decrypted1)
console.log("Розшифрований текст збережено у файлі Decrypted1.txt")
console.log('Розшифровка методом другим знаходження ключа...')
const decrypted2 = vizhener.decryptReliable({method: 2})
fs.writeFileSync('Decrypted2.txt', decrypted2)
console.log("Розшифрований текст збережено у файлі Decrypted2.txt")
